version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mini_blog
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
